services:
  devnology-database-docker:
    image: postgres
    container_name: devnology-database-docker
    restart: always
    ports: 
      - 2345:5432
    env_file:
      - .env.docker
    volumes:
      - devnology-pg:/var/lib/postgresql/data

  devnology-docker:
    container_name: devnology-docker
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.docker
    depends_on:
      - devnology-database-docker

volumes:
  devnology-pg: